{{ if .Values.persistence.enabled }}
{{ range .Values.persistence.claims }}
{{ if or ( ne .name "db") (and (eq .name "db") (eq $.Values.containers.db.type "internal")) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-{{ .name }}
  {{- if eq $.Values.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes: 
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
  {{ if .storageClass }}
  {{ if eq "-" .storageClass }}
  storageClassName: ""
  {{ else }}
  storageClassName: {{ .storageClass }}
  {{ end }}
  {{ end }}
{{ end }}
---
{{ end }}
{{ end }}
